services:
  prism:
    image: prism:latest
    build:
      context: .
      dockerfile: prism/Dockerfile
      target: runner
    container_name: prism
    networks:
      prism-network:
        ipv4_address: 172.18.0.10
    ports:
      - "8080:8080"
      # - "443:443"
    volumes:
      - ./.secret:/secret
      - ./prism.yml:/app/prism.yml:ro
      # - ./.prism/hello.yml:/app/prism.yml:ro
      # - ./.prism/simple.yml:/app/prism.yml:ro
      # - ./.prism/subdomain.yml:/app/prism.yml:ro

  backend1:
    image: nginx:alpine
    container_name: backend1
    networks:
      prism-network:
        ipv4_address: 172.18.0.20

  quartz:
    image: quartz:latest
    build:
      context: .
      dockerfile: quartz/Dockerfile
    container_name: quartz
    networks:
      prism-network:
        ipv4_address: 172.18.0.30

networks:
  prism-network:
    name: prism-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1